version: "3"
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - /opt/appdata/authelia:/config
    environment:
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.yourdomain.com`)
      - traefik.http.routers.authelia.entrypoints=https
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=cloudflare
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.yourdomain.com
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    container_name: authelia-redis
    image: bitnami/redis:latest
    expose:
      - 6379
    volumes:
      - /opt/appdata/authelia/redis:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=YOUR_REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - proxy
    restart: unless-stopped

  mariadb:
    container_name: authelia-mariadb
    image: linuxserver/mariadb:latest
    expose:
      - 3306
    volumes:
      - /opt/appdata/authelia/mariadb:/config
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=authelia
      - MYSQL_USER=authelia
      - MYSQL_PASSWORD=YOUR_MYSQL_USER_PASSWORD
      - TZ=America/New_York
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
